"""Add Goal and GoalMedia models

Revision ID: 45fa650feb73
Revises: 6572f1873a46
Create Date: 2025-11-14 14:13:51.259668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fa650feb73'
down_revision = '6572f1873a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motivation_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('cover_image_path', sa.String(length=300), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motivation_item')
    # ### end Alembic commands ###
