"""Add Goal and GoalMedia models

Revision ID: 6572f1873a46
Revises: 7771d42350fd
Create Date: 2025-11-14 13:39:13.747717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6572f1873a46'
down_revision = '7771d42350fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('current_progress', sa.Float(), nullable=False),
    sa.Column('target_progress', sa.Float(), nullable=False),
    sa.Column('progress_unit', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('is_before_photo', sa.Boolean(), nullable=True),
    sa.Column('is_after_photo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_media')
    op.drop_table('goal')
    # ### end Alembic commands ###
