"""Add gamification models for tournament

Revision ID: 9aec3e085548
Revises: 1b50b7f7ca81
Create Date: 2025-11-11 05:59:31.029354
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aec3e085548'
down_revision = '1b50b7f7ca81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'challenge',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('level_requirement', sa.Integer(), nullable=False),
        sa.Column('xp_reward', sa.Integer(), nullable=False),
        sa.Column('task_details', sa.String(length=300), nullable=False),
        sa.Column('time_limit', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'user_challenge',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('challenge_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user_profile.id']),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('experience_points', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('experience_points')
        batch_op.drop_column('level')

    op.drop_table('user_challenge')
    op.drop_table('challenge')
    # ### end Alembic commands ###
